# required
base_frame: base_footprint
map_frame: map

# optional
odom_frame: odom # optional - recommended


max_distance: 1.0

# adjust max distance dependend of the state of localization
adaptive_max_dist: True
adaptive_max_dist_min: 0.15

# rates
tf_rate: 50
corr_rate_max: 600

# describe your sensor setup here
sensors: # list of range sensors - at least one is required
  velodyne:
    topic: velodyne_points
    type: spherical
    model:
      range_min: 0.5
      range_max: 130.0
      phi_min: -0.261799067259
      phi_inc: 0.03490658503988659
      phi_N: 16
      theta_min: -3.14159011841
      theta_inc: 0.01431249500496489 # (2*pi)/439 instead of (2*pi)/440 
      theta_N: 440
    micp:
      max_dist: 0.5
      weight: 10
      backend: optix
  # sick:
  #   topic: scan
  #   micp:
  #     weight: 2.0
  #     backend: optix
  # kinect:
  #   topic: kinect/depth/image_raw
  #   model_topic: kinect/rgb/camera_info
  #   micp:
  #     max_dist: 0.5
  #     weight: 2.0
  #     backend: optix
  # wheels: # pull robot to the mesh
  #   ranges: [0.2, 0.2, 0.2, 0.2]
  #   type: ondn
  #   frame: base_footprint
  #   model:
  #     width: 4
  #     height: 1
  #     range_min: 0.0
  #     range_max: 10.0
  #     origs: [
  #         [ 0.2,  0.15, 0.2], # front left 
  #         [ 0.2, -0.15, 0.2], # front right
  #         [-0.2,  0.15, 0.2], # rear left
  #         [-0.2, -0.15, 0.2]  # rear right
  #       ]
  #     dirs: [ # pointing downwards
  #         [0.0, 0.0, -1.0]
  #         [0.0, 0.0, -1.0],
  #         [0.0, 0.0, -1.0],
  #         [0.0, 0.0, -1.0]
  #       ]
  #   micp:
  #     max_dist: 1.0
  #     weight: 1
  #     backend: embree
  # base_footprint:
  #   ranges: [0.2]
  #   type: ondn
  #   frame: base_footprint
  #   model:
  #     width: 1
  #     height: 1
  #     range_min: 0.0
  #     range_max: 10.0
  #     origs: [
  #       [0.0, 0.0, 0.2]
  #     ]
  #     dirs: [
  #       [0.0, 0.0, -1.0]
  #     ]
  #   micp:
  #     max_dist: 1.0
  #     weight: 1.0
  #     backend: embree



# TESTING async performance
poses: 1